language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_install:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog
